[config]
# link文件夹重命名备份
backupLinkFolder = false

# 清空备份的文件夹
clearBackupFolder = true

#当target文件不存在时，创建
createTargetFolder = true

#当target文件自动分配
targetFolders=[
'v:/useless/Z/Z[0-9]',
]

[pathAlias]
#build in path variable
# UserHome
# Temp
useless='V:/useless/'
chromeCache='V:/chrome_cache'
firefoxCache='V:/firefox_cache'
appDataRoaming='{UserHome}/AppData/Roaming'
appDataLocal='{UserHome}/AppData/Local'
QQDataHome='{UserHome}/AppData/Roaming/Tencent'

[[symbolic]]
target = '{useless}/Z'
link = [
'filw@v:/|log.|/tt',
]
