[config]
# link文件夹重命名备份
backupLinkFolder = false

# 清空备份的文件夹
clearBackupFolder = true

#当target文件不存在时，创建
createTargetFolder = true

[pathAlias]
#build in path variable
# UserHome
# Temp
useless='V:/useless'
chromeCache='V:/chrome_cache'
firefoxCache='V:/firefox_cache'
appDataRoaming='{UserHome}/AppData/Roaming'
appDataLocal='{UserHome}/AppData/Local'
QQDataHome='{UserHome}/AppData/Roaming/Tencent'


#开发工具
[[symbolic]]
target = '{useless}/Z'
link = [
'w@E:/|eclipse.*?workspace|/.metadata/.plugins/org.eclipse.jdt.core',
'w@E:/|eclipse.*?workspace|/.metadata/.plugins/org.eclipse.core.resources/.history',
'w@E:/|eclipse.*?workspace|/.metadata/.plugins/org.eclipse.m2e.logback.configuration',
]


