[config]
# normal link文件夹重命名备份
backupLinkFolder = true

# 清空备份的文件夹
clearBackupFolder = false

#当target文件不存在时，创建
createTargetFolder = true

[pathAlias]
#build in path variable
# UserHome  win7 like C:/Users/changsheng
# Temp
useless='V:/useless'
chromeCache='V:/chrome_cache'
firefoxCache='V:/firefox_cache'
appDataRoaming='{UserHome}/AppData/Roaming'
appDataLocal='{UserHome}/AppData/Local'
QQDataHome='{UserHome}/AppData/Roaming/Tencent'

[[symbolic]]
skip=false
target = 'v:/uselessTest/A'
link = [
'lf@{useless}/aaa',
'w@{useless}/U',
'w@{useless}/V',
'w@{useless}/W',
'w@{useless}/Z',
'w@{useless}/Y',
'w@{useless}/X',
]

[[symbolic]]
target = 'v:/uselessTest/B'
link = [
'w@{useless}/L',
'w@{useless}/M',
'w@{useless}/N',
'w@{useless}/O',
'w@{useless}/P',
'w@{useless}/Q',
]