[config]
# 原始文件夹重命名备份
backupLinkFolder = false

# 清空原始文件夹
clearBackupFolder = true

#当目录文件夹无效时，跳过
createTargetFolder = false

[pathAlias]
#build in path variable
# UserHome
# Temp
useless='C:/useless'
chrome_cache='V:/chrome_cache'
firefox_cache='V:/firefox_cache'

[[symbolic]]
action="ignore"
target = '{useless}/AAA'
link = [
'bclf@d:/|\d+$|/bin',
'v:/|cache$|'
]

[[symbolic]]
action="recovery"
target = '{useless}/B'
link = [
'd:/|\d+$|/bin',
'{chrome_cache}/|chrome$|'
]