[config]
# link文件夹重命名备份
backupLinkFolder = false

# 清空备份的文件夹
clearBackupFolder = true

#当target文件不存在时，创建
createTargetFolder = true

[pathAlias]
#build in path variable
# UserHome  win7 like C:\Users\changsheng
# Temp
useless='C:/useless'
chrome_cache='V:/chrome_cache'
firefox_cache='V:/firefox_cache'

[[symbolic]]
skip=true
target = '{useless}/AAA'
link = [
'bc@d:/|\d+$|/bin',
'v:/|cache$|'
]

[[symbolic]]
target = '{useless}/B'
link = [
'd:/|\d+$|/bin',
'{chrome_cache}/|chrome$|'
]