[config]
# link文件夹重命名备份
backupLinkFolder = false

# 清空备份的文件夹
clearBackupFolder = true

#当target文件不存在时，创建
createTargetFolder = true

[pathAlias]
#build in path variable
# UserHome  win7 like C:\Users\changsheng
# Temp
Useless='C:/useless'
ChromeCache='V:/chrome_cache'
FirefoxCache='V:/firefox_cache'
QQData='{UserHome}/AppData/Roaming/Tencent'

[[symbolic]]
skip=true
target = '{Useless}/AAA'
link = [
'bc@d:/|\d+$|/bin',
'v:/|cache$|'
]

[[symbolic]]
target = '{Useless}/B'
link = [
'd:/|\d+$|/bin',
'{ChromeCache}/|chrome$|'
]